# .github/workflows/deploy.yml

name: Test EC2 Windows SSH Connection

on:
  push:
    branches: [ master ]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Test SSH Connection to EC2
      uses: appleboy/ssh-action@master # 또는 @master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        debug: true
        script: |
          echo "Attempting to connect via SSH..."
          echo "Connection successful! Current user is $(whoami)"
          echo "Current directory is $(pwd)"
          echo "Listing files in current directory:"
          ls -la